spring:
  application:
    name: PriceAi

  datasource:
    url: jdbc:postgresql://db:5432/priceai
    username: rafael
    password: mamute
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: false

server:
  port: 8080

gemini:
  url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent"